// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdkapi.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from sdkapi.proto</summary>
public static partial class SdkapiReflection {

  #region Descriptor
  /// <summary>File descriptor for sdkapi.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SdkapiReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxzZGthcGkucHJvdG8aDXNka2JlYW4ucHJvdG8iZAoQUGF5bWVudFRva2Vu",
          "UmVzcBIUCgxhY2Nlc3NfdG9rZW4YASABKAkSEgoKdG9rZW5fdHlwZRgCIAEo",
          "CRISCgpleHBpcmVzX2luGAMgASgFEhIKCmNyZWF0ZWRfYXQYBCABKAMibgoV",
          "UGF5bWVudENyZWF0ZU9yZGVyUmVxEg8KB3ZlcnNpb24YASABKAkSIgoFaXRl",
          "bXMYAiADKAsyEy5QYXltZW50T3JkZXJJdGVtUGISIAoGY3VzdG9tGAMgASgL",
          "MhAuUGF5bWVudEN1c3RvbVBiIjgKFlBheW1lbnRDcmVhdGVPcmRlclJlc3AS",
          "DwoHb3JkZXJObxgBIAEoCRINCgV0b2tlbhgCIAEoCSIpChZQYXltZW50R2V0",
          "T3JkZXJJbmZvUmVxEg8KB29yZGVyTm8YASABKAki7QEKF1BheW1lbnRHZXRP",
          "cmRlckluZm9SZXNwEg8KB29yZGVyTm8YASABKAkSDwoHYXBwQ29kZRgCIAEo",
          "CRIOCgZzdGF0dXMYAyABKAkSDgoGdXNlcklkGAQgASgFEhMKC3BheW1lbnRD",
          "b2RlGAUgASgFEhIKCnJldHJ5Q291bnQYBiABKAUSDgoGY3VzdG9tGAcgASgJ",
          "Eg0KBWVycm9yGAggASgFEhEKCWNyZWF0ZWRBdBgJIAEoCRIRCgl1cGRhdGVk",
          "QXQYCiABKAkSIgoFaXRlbXMYCyADKAsyEy5QYXltZW50T3JkZXJJdGVtUGIi",
          "JAoRUGF5bWVudERlbGl2ZXJSZXESDwoHb3JkZXJObxgBIAEoCUIWCgpjb20u",
          "Y2IubXNnQghQQlNka0FwaWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::SdkbeanReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PaymentTokenResp), global::PaymentTokenResp.Parser, new[]{ "AccessToken", "TokenType", "ExpiresIn", "CreatedAt" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PaymentCreateOrderReq), global::PaymentCreateOrderReq.Parser, new[]{ "Version", "Items", "Custom" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PaymentCreateOrderResp), global::PaymentCreateOrderResp.Parser, new[]{ "OrderNo", "Token" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PaymentGetOrderInfoReq), global::PaymentGetOrderInfoReq.Parser, new[]{ "OrderNo" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PaymentGetOrderInfoResp), global::PaymentGetOrderInfoResp.Parser, new[]{ "OrderNo", "AppCode", "Status", "UserId", "PaymentCode", "RetryCount", "Custom", "Error", "CreatedAt", "UpdatedAt", "Items" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PaymentDeliverReq), global::PaymentDeliverReq.Parser, new[]{ "OrderNo" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///支付全局token
/// </summary>
public sealed partial class PaymentTokenResp : pb::IMessage<PaymentTokenResp> {
  private static readonly pb::MessageParser<PaymentTokenResp> _parser = new pb::MessageParser<PaymentTokenResp>(() => new PaymentTokenResp());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PaymentTokenResp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SdkapiReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentTokenResp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentTokenResp(PaymentTokenResp other) : this() {
    accessToken_ = other.accessToken_;
    tokenType_ = other.tokenType_;
    expiresIn_ = other.expiresIn_;
    createdAt_ = other.createdAt_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentTokenResp Clone() {
    return new PaymentTokenResp(this);
  }

  /// <summary>Field number for the "access_token" field.</summary>
  public const int AccessTokenFieldNumber = 1;
  private string accessToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AccessToken {
    get { return accessToken_; }
    set {
      accessToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "token_type" field.</summary>
  public const int TokenTypeFieldNumber = 2;
  private string tokenType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string TokenType {
    get { return tokenType_; }
    set {
      tokenType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "expires_in" field.</summary>
  public const int ExpiresInFieldNumber = 3;
  private int expiresIn_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ExpiresIn {
    get { return expiresIn_; }
    set {
      expiresIn_ = value;
    }
  }

  /// <summary>Field number for the "created_at" field.</summary>
  public const int CreatedAtFieldNumber = 4;
  private long createdAt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long CreatedAt {
    get { return createdAt_; }
    set {
      createdAt_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PaymentTokenResp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PaymentTokenResp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AccessToken != other.AccessToken) return false;
    if (TokenType != other.TokenType) return false;
    if (ExpiresIn != other.ExpiresIn) return false;
    if (CreatedAt != other.CreatedAt) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (AccessToken.Length != 0) hash ^= AccessToken.GetHashCode();
    if (TokenType.Length != 0) hash ^= TokenType.GetHashCode();
    if (ExpiresIn != 0) hash ^= ExpiresIn.GetHashCode();
    if (CreatedAt != 0L) hash ^= CreatedAt.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (AccessToken.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(AccessToken);
    }
    if (TokenType.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(TokenType);
    }
    if (ExpiresIn != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ExpiresIn);
    }
    if (CreatedAt != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(CreatedAt);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (AccessToken.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessToken);
    }
    if (TokenType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TokenType);
    }
    if (ExpiresIn != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpiresIn);
    }
    if (CreatedAt != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreatedAt);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PaymentTokenResp other) {
    if (other == null) {
      return;
    }
    if (other.AccessToken.Length != 0) {
      AccessToken = other.AccessToken;
    }
    if (other.TokenType.Length != 0) {
      TokenType = other.TokenType;
    }
    if (other.ExpiresIn != 0) {
      ExpiresIn = other.ExpiresIn;
    }
    if (other.CreatedAt != 0L) {
      CreatedAt = other.CreatedAt;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          AccessToken = input.ReadString();
          break;
        }
        case 18: {
          TokenType = input.ReadString();
          break;
        }
        case 24: {
          ExpiresIn = input.ReadInt32();
          break;
        }
        case 32: {
          CreatedAt = input.ReadInt64();
          break;
        }
      }
    }
  }

}

public sealed partial class PaymentCreateOrderReq : pb::IMessage<PaymentCreateOrderReq> {
  private static readonly pb::MessageParser<PaymentCreateOrderReq> _parser = new pb::MessageParser<PaymentCreateOrderReq>(() => new PaymentCreateOrderReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PaymentCreateOrderReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SdkapiReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentCreateOrderReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentCreateOrderReq(PaymentCreateOrderReq other) : this() {
    version_ = other.version_;
    items_ = other.items_.Clone();
    Custom = other.custom_ != null ? other.Custom.Clone() : null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentCreateOrderReq Clone() {
    return new PaymentCreateOrderReq(this);
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 1;
  private string version_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Version {
    get { return version_; }
    set {
      version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "items" field.</summary>
  public const int ItemsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::PaymentOrderItemPb> _repeated_items_codec
      = pb::FieldCodec.ForMessage(18, global::PaymentOrderItemPb.Parser);
  private readonly pbc::RepeatedField<global::PaymentOrderItemPb> items_ = new pbc::RepeatedField<global::PaymentOrderItemPb>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::PaymentOrderItemPb> Items {
    get { return items_; }
  }

  /// <summary>Field number for the "custom" field.</summary>
  public const int CustomFieldNumber = 3;
  private global::PaymentCustomPb custom_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::PaymentCustomPb Custom {
    get { return custom_; }
    set {
      custom_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PaymentCreateOrderReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PaymentCreateOrderReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Version != other.Version) return false;
    if(!items_.Equals(other.items_)) return false;
    if (!object.Equals(Custom, other.Custom)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Version.Length != 0) hash ^= Version.GetHashCode();
    hash ^= items_.GetHashCode();
    if (custom_ != null) hash ^= Custom.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Version.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Version);
    }
    items_.WriteTo(output, _repeated_items_codec);
    if (custom_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Custom);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Version.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
    }
    size += items_.CalculateSize(_repeated_items_codec);
    if (custom_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Custom);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PaymentCreateOrderReq other) {
    if (other == null) {
      return;
    }
    if (other.Version.Length != 0) {
      Version = other.Version;
    }
    items_.Add(other.items_);
    if (other.custom_ != null) {
      if (custom_ == null) {
        custom_ = new global::PaymentCustomPb();
      }
      Custom.MergeFrom(other.Custom);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Version = input.ReadString();
          break;
        }
        case 18: {
          items_.AddEntriesFrom(input, _repeated_items_codec);
          break;
        }
        case 26: {
          if (custom_ == null) {
            custom_ = new global::PaymentCustomPb();
          }
          input.ReadMessage(custom_);
          break;
        }
      }
    }
  }

}

public sealed partial class PaymentCreateOrderResp : pb::IMessage<PaymentCreateOrderResp> {
  private static readonly pb::MessageParser<PaymentCreateOrderResp> _parser = new pb::MessageParser<PaymentCreateOrderResp>(() => new PaymentCreateOrderResp());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PaymentCreateOrderResp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SdkapiReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentCreateOrderResp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentCreateOrderResp(PaymentCreateOrderResp other) : this() {
    orderNo_ = other.orderNo_;
    token_ = other.token_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentCreateOrderResp Clone() {
    return new PaymentCreateOrderResp(this);
  }

  /// <summary>Field number for the "orderNo" field.</summary>
  public const int OrderNoFieldNumber = 1;
  private string orderNo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string OrderNo {
    get { return orderNo_; }
    set {
      orderNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 2;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PaymentCreateOrderResp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PaymentCreateOrderResp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (OrderNo != other.OrderNo) return false;
    if (Token != other.Token) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (OrderNo.Length != 0) hash ^= OrderNo.GetHashCode();
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (OrderNo.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(OrderNo);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Token);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (OrderNo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderNo);
    }
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PaymentCreateOrderResp other) {
    if (other == null) {
      return;
    }
    if (other.OrderNo.Length != 0) {
      OrderNo = other.OrderNo;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          OrderNo = input.ReadString();
          break;
        }
        case 18: {
          Token = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class PaymentGetOrderInfoReq : pb::IMessage<PaymentGetOrderInfoReq> {
  private static readonly pb::MessageParser<PaymentGetOrderInfoReq> _parser = new pb::MessageParser<PaymentGetOrderInfoReq>(() => new PaymentGetOrderInfoReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PaymentGetOrderInfoReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SdkapiReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentGetOrderInfoReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentGetOrderInfoReq(PaymentGetOrderInfoReq other) : this() {
    orderNo_ = other.orderNo_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentGetOrderInfoReq Clone() {
    return new PaymentGetOrderInfoReq(this);
  }

  /// <summary>Field number for the "orderNo" field.</summary>
  public const int OrderNoFieldNumber = 1;
  private string orderNo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string OrderNo {
    get { return orderNo_; }
    set {
      orderNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PaymentGetOrderInfoReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PaymentGetOrderInfoReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (OrderNo != other.OrderNo) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (OrderNo.Length != 0) hash ^= OrderNo.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (OrderNo.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(OrderNo);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (OrderNo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderNo);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PaymentGetOrderInfoReq other) {
    if (other == null) {
      return;
    }
    if (other.OrderNo.Length != 0) {
      OrderNo = other.OrderNo;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          OrderNo = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class PaymentGetOrderInfoResp : pb::IMessage<PaymentGetOrderInfoResp> {
  private static readonly pb::MessageParser<PaymentGetOrderInfoResp> _parser = new pb::MessageParser<PaymentGetOrderInfoResp>(() => new PaymentGetOrderInfoResp());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PaymentGetOrderInfoResp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SdkapiReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentGetOrderInfoResp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentGetOrderInfoResp(PaymentGetOrderInfoResp other) : this() {
    orderNo_ = other.orderNo_;
    appCode_ = other.appCode_;
    status_ = other.status_;
    userId_ = other.userId_;
    paymentCode_ = other.paymentCode_;
    retryCount_ = other.retryCount_;
    custom_ = other.custom_;
    error_ = other.error_;
    createdAt_ = other.createdAt_;
    updatedAt_ = other.updatedAt_;
    items_ = other.items_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentGetOrderInfoResp Clone() {
    return new PaymentGetOrderInfoResp(this);
  }

  /// <summary>Field number for the "orderNo" field.</summary>
  public const int OrderNoFieldNumber = 1;
  private string orderNo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string OrderNo {
    get { return orderNo_; }
    set {
      orderNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "appCode" field.</summary>
  public const int AppCodeFieldNumber = 2;
  private string appCode_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AppCode {
    get { return appCode_; }
    set {
      appCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 3;
  private string status_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Status {
    get { return status_; }
    set {
      status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 4;
  private int userId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "paymentCode" field.</summary>
  public const int PaymentCodeFieldNumber = 5;
  private int paymentCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PaymentCode {
    get { return paymentCode_; }
    set {
      paymentCode_ = value;
    }
  }

  /// <summary>Field number for the "retryCount" field.</summary>
  public const int RetryCountFieldNumber = 6;
  private int retryCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RetryCount {
    get { return retryCount_; }
    set {
      retryCount_ = value;
    }
  }

  /// <summary>Field number for the "custom" field.</summary>
  public const int CustomFieldNumber = 7;
  private string custom_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Custom {
    get { return custom_; }
    set {
      custom_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 8;
  private int error_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  /// <summary>Field number for the "createdAt" field.</summary>
  public const int CreatedAtFieldNumber = 9;
  private string createdAt_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string CreatedAt {
    get { return createdAt_; }
    set {
      createdAt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "updatedAt" field.</summary>
  public const int UpdatedAtFieldNumber = 10;
  private string updatedAt_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UpdatedAt {
    get { return updatedAt_; }
    set {
      updatedAt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "items" field.</summary>
  public const int ItemsFieldNumber = 11;
  private static readonly pb::FieldCodec<global::PaymentOrderItemPb> _repeated_items_codec
      = pb::FieldCodec.ForMessage(90, global::PaymentOrderItemPb.Parser);
  private readonly pbc::RepeatedField<global::PaymentOrderItemPb> items_ = new pbc::RepeatedField<global::PaymentOrderItemPb>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::PaymentOrderItemPb> Items {
    get { return items_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PaymentGetOrderInfoResp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PaymentGetOrderInfoResp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (OrderNo != other.OrderNo) return false;
    if (AppCode != other.AppCode) return false;
    if (Status != other.Status) return false;
    if (UserId != other.UserId) return false;
    if (PaymentCode != other.PaymentCode) return false;
    if (RetryCount != other.RetryCount) return false;
    if (Custom != other.Custom) return false;
    if (Error != other.Error) return false;
    if (CreatedAt != other.CreatedAt) return false;
    if (UpdatedAt != other.UpdatedAt) return false;
    if(!items_.Equals(other.items_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (OrderNo.Length != 0) hash ^= OrderNo.GetHashCode();
    if (AppCode.Length != 0) hash ^= AppCode.GetHashCode();
    if (Status.Length != 0) hash ^= Status.GetHashCode();
    if (UserId != 0) hash ^= UserId.GetHashCode();
    if (PaymentCode != 0) hash ^= PaymentCode.GetHashCode();
    if (RetryCount != 0) hash ^= RetryCount.GetHashCode();
    if (Custom.Length != 0) hash ^= Custom.GetHashCode();
    if (Error != 0) hash ^= Error.GetHashCode();
    if (CreatedAt.Length != 0) hash ^= CreatedAt.GetHashCode();
    if (UpdatedAt.Length != 0) hash ^= UpdatedAt.GetHashCode();
    hash ^= items_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (OrderNo.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(OrderNo);
    }
    if (AppCode.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(AppCode);
    }
    if (Status.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Status);
    }
    if (UserId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(UserId);
    }
    if (PaymentCode != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(PaymentCode);
    }
    if (RetryCount != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(RetryCount);
    }
    if (Custom.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Custom);
    }
    if (Error != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Error);
    }
    if (CreatedAt.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(CreatedAt);
    }
    if (UpdatedAt.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(UpdatedAt);
    }
    items_.WriteTo(output, _repeated_items_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (OrderNo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderNo);
    }
    if (AppCode.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppCode);
    }
    if (Status.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
    }
    if (UserId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
    }
    if (PaymentCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PaymentCode);
    }
    if (RetryCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RetryCount);
    }
    if (Custom.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Custom);
    }
    if (Error != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
    }
    if (CreatedAt.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CreatedAt);
    }
    if (UpdatedAt.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UpdatedAt);
    }
    size += items_.CalculateSize(_repeated_items_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PaymentGetOrderInfoResp other) {
    if (other == null) {
      return;
    }
    if (other.OrderNo.Length != 0) {
      OrderNo = other.OrderNo;
    }
    if (other.AppCode.Length != 0) {
      AppCode = other.AppCode;
    }
    if (other.Status.Length != 0) {
      Status = other.Status;
    }
    if (other.UserId != 0) {
      UserId = other.UserId;
    }
    if (other.PaymentCode != 0) {
      PaymentCode = other.PaymentCode;
    }
    if (other.RetryCount != 0) {
      RetryCount = other.RetryCount;
    }
    if (other.Custom.Length != 0) {
      Custom = other.Custom;
    }
    if (other.Error != 0) {
      Error = other.Error;
    }
    if (other.CreatedAt.Length != 0) {
      CreatedAt = other.CreatedAt;
    }
    if (other.UpdatedAt.Length != 0) {
      UpdatedAt = other.UpdatedAt;
    }
    items_.Add(other.items_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          OrderNo = input.ReadString();
          break;
        }
        case 18: {
          AppCode = input.ReadString();
          break;
        }
        case 26: {
          Status = input.ReadString();
          break;
        }
        case 32: {
          UserId = input.ReadInt32();
          break;
        }
        case 40: {
          PaymentCode = input.ReadInt32();
          break;
        }
        case 48: {
          RetryCount = input.ReadInt32();
          break;
        }
        case 58: {
          Custom = input.ReadString();
          break;
        }
        case 64: {
          Error = input.ReadInt32();
          break;
        }
        case 74: {
          CreatedAt = input.ReadString();
          break;
        }
        case 82: {
          UpdatedAt = input.ReadString();
          break;
        }
        case 90: {
          items_.AddEntriesFrom(input, _repeated_items_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class PaymentDeliverReq : pb::IMessage<PaymentDeliverReq> {
  private static readonly pb::MessageParser<PaymentDeliverReq> _parser = new pb::MessageParser<PaymentDeliverReq>(() => new PaymentDeliverReq());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PaymentDeliverReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SdkapiReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentDeliverReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentDeliverReq(PaymentDeliverReq other) : this() {
    orderNo_ = other.orderNo_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PaymentDeliverReq Clone() {
    return new PaymentDeliverReq(this);
  }

  /// <summary>Field number for the "orderNo" field.</summary>
  public const int OrderNoFieldNumber = 1;
  private string orderNo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string OrderNo {
    get { return orderNo_; }
    set {
      orderNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PaymentDeliverReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PaymentDeliverReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (OrderNo != other.OrderNo) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (OrderNo.Length != 0) hash ^= OrderNo.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (OrderNo.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(OrderNo);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (OrderNo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderNo);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PaymentDeliverReq other) {
    if (other == null) {
      return;
    }
    if (other.OrderNo.Length != 0) {
      OrderNo = other.OrderNo;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          OrderNo = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
