
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Quality
    {
        /// <summary>
        /// 最高品质
        /// </summary>
        A = 0,
        /// <summary>
        /// 黑色
        /// </summary>
        B = 1,
        /// <summary>
        /// 蓝色
        /// </summary>
        C = 2,
        /// <summary>
        /// 最差品质
        /// </summary>
        D = 3,
    }

} 

